config/routes.rb
Rails.application.routes.draw do
  root 'home#input'
  get 'home/input' => 'home#input', :as => 'input'
  get 'home/output' => 'home#output', :as => 'output'
  get 'home/serialize' => 'home#serialize_db', :as => 'serialize'
  get 'home/last_record' => 'home#last_rec', :as => 'lastrec'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
    validates :request, uniqueness: true

    class << self
        def compute(request)
            (request + 1).times.filter do |i|
                square = (i**2).to_s
                square == square.reverse
            end
        end

        def create_or_get_by_request(request)
            return (res = find_by(request: data)) unless res.nil?
            create(request: request, response: Result.compute(request))
        end
    end

    def response
        ActiveSupport::JSON.decode(super)
      end
      
    def response=(value)
        super(ActiveSupport::JSON.encode(value))
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_params, only: %(output)

  def input; end

  def output
    @result = Result.create_or_get_by_request(@request)
  end

  def serialize_db
    render xml: Result.all.to_xml
  end

  def last_rec
    render xml: (res = Result.last).nil? ? ["База данных пуста"].to_xml : res.to_xml
  end

  protected

  def check_params
    @request = Integer(params[:txt], exception: false)
    @error = 'Введено не число' if @request.nil?
    render :output unless @error.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/input.html.erb
<div class="form-io">
    <b>Лабораторная работа №11</b>
    <%= form_tag('/home/output', :method => 'get') do %>
        <%= text_field_tag :txt, '', placeholder: "Введите число", class: 'textarea', id: 'input-field'%>
        <%= submit_tag 'Найти', class: 'button', id: 'submit-but' %>
    <% end %>
    
</div>
<div class="form-buttons">
    <%= link_to '<button class="db-button"><b>База данных</b></button>'.html_safe, serialize_path  %>
    <%= link_to '<button class="db-button"><b>Последняя запись</b></button>'.html_safe, lastrec_path  %>
</div>

app/views/home/output.html.erb
<div class="form-io">
    <% if @result.nil? %>
        <b>Ошибка ввода</b><br>
    <%else%>
        <b>Результат</b>
        <table>
            <tr>
                <th>Индекс</th>
                <th>Число</th>
                <th>Квадрат</th>
            </tr>
            <% @result.response.each_with_index do |num, index| %>
                <tr>
                    <td><%= index+1 %></td>
                    <td><%= num %></td>
                    <td><%= num**2 %></td>
                </tr>
            <% end %>
        </table>
    <%end%>
    <%= link_to '<button class="button">Назад</button>'.html_safe, input_path  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laba11</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>